steps:
# Install & test
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'hello-world-1'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'hello-world-1'
# Fetch encrypted key from encrypted bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://secrets_bucket/id_rsa.enc', 'id_rsa.enc']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://secrets_bucket/known_hosts', 'known_hosts']
# Decrypt key
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - kms
    - decrypt
    - --ciphertext-file=id_rsa.enc
    - --plaintext-file=/root/.ssh/id_rsa
    - --location=global
    - --keyring=test
    - --key=github-key
    volumes:
    - name: 'ssh'
      path: /root/.ssh
# Set up github credentials
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      rm id_rsa.enc
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      mv known_hosts /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh
# Set up github identity & commit changes
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git config user.email "eva.demers-brett@cds-snc.ca"
      git config user.name "Mr Pinchy"
      git status
      # git add hello_world.txt
      # git commit -m "test"
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  