steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: 'hello-world-1'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  dir: 'hello-world-1'
  args: ['run', 'test']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'hello-world-1'
  args: ['build', 
         '-t', 'gcr.io/$PROJECT_ID/hello-world-1:$BRANCH_NAME-$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/hello-world-1:latest',
         '-f', 'Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/hello-world-1:$BRANCH_NAME-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/hello-world-1:latest'