steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://secrets_bucket/id_rsa.enc', 'secrets/id_rsa.enc']
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      ls