steps:
# PART 1
# Install, test & build image
- name: 'gcr.io/cloud-builders/npm'
  dir: 'hello-world-1'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  dir: 'hello-world-1'
  args: ['run', 'test']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'hello-world-1'
  args: ['build', 
        '-t', 'gcr.io/$PROJECT_ID/hello-world-1:$BRANCH_NAME-$SHORT_SHA',
        '-t', 'gcr.io/$PROJECT_ID/hello-world-1:latest',
        '-f', 'Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/hello-world-1:$BRANCH_NAME-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/hello-world-1:latest'
# PART 2
# Use Kustomize to update image tag
# Build to create deployment file
- name: 'gcr.io/$PROJECT_ID/kustomize'
  dir: 'hello-world-1/manifests'
  args:
  - '-c'
  - |
    kustomize edit set imagetag gcr.io/$PROJECT_ID/hello-world-1:$BRANCH_NAME-$SHORT_SHA
    kustomize build . > deploy/deploy.yaml

# Fetch encrypted key from encrypted bucket
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['cp', 'gs://secrets_bucket/id_rsa.enc', 'id_rsa.enc']
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['cp', 'gs://secrets_bucket/known_hosts', 'known_hosts']
# # Decrypt key
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#     - kms
#     - decrypt
#     - --ciphertext-file=id_rsa.enc
#     - --plaintext-file=/root/.ssh/id_rsa
#     - --location=global
#     - --keyring=test
#     - --key=github-key
#     volumes:
#     - name: 'ssh'
#       path: /root/.ssh
# # Set up github credentials
#   - name: 'gcr.io/cloud-builders/git'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       rm id_rsa.enc
#       chmod 600 /root/.ssh/id_rsa
#       cat <<EOF >/root/.ssh/config
#       Hostname github.com
#       IdentityFile /root/.ssh/id_rsa
#       EOF
#       mv known_hosts /root/.ssh/known_hosts
#     volumes:
#     - name: 'ssh'
#       path: /root/.ssh
# # Set up github identity & commit changes
#   - name: 'gcr.io/cloud-builders/git'
#     entrypoint: 'bash'
#     args:
#     - '-c'
#     - |
#       git config user.email "mr.pinchy@cds-snc.ca"
#       git config user.name "Mr Pinchy"
#       git status
#     volumes:
#     - name: 'ssh'
#       path: /root/.ssh
  