---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-web-2
  annotations:
    flux.weave.works/automated: "true"
  name: hello-world-web-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-web-2
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world-web-2
    spec:
      containers:
      - image: gcr.io/gcr-test-223818/hello-world-2:master-5f03a6a
        name: hello-world-web-2
        resources: {}
status: {}
